<?php

use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\user\UserInterface;

/**
 * @implements hook_user_login.
 */
function customblock_user_login(UserInterface $account) {
  // using custom user_redirect service to redirect user to the 
  \Drupal::service('customblock.user_redirect')->setLoginRedirection('/custom-welcome-page', 'administrator');
}

/**
 * @implements hook_theme.
 */
function customblock_theme($existing, $type, $theme, $path)  {
  return [
    'artifacts_theme' => [
      'variables' => [
        'artifacts' => NULL,
      ]
    ],
    'block__customblock_artifacts' => [
      'variables' => [
        'artifacts' => NULL,
      ]
    ],
  ];
}

/**
 * Implements theme_suggestions_hook.
 */
function customblock_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // Checking for artifacts block.
  // Adding template suggestions for the artifacts block.
  if ($variables['elements'] && $variables['elements']['#plugin_id'] == "customblock_artifacts" ) {
    $block_plugin_id = $variables['elements']['#plugin_id'];
    $suggestions[] = 'block__' . $block_plugin_id;
    $suggestions[] = 'artifacts_theme';
  }
}