<?php

use Drupal\Core\Routing\TrustedRedirectResponse;
use Drupal\user\UserInterface;

/**
 * @implements hook_user_login.
 */
function customblock_user_login(UserInterface $account) {
  // using custom user_redirect service to redirect user to the 
  \Drupal::service('customblock.user_redirect')->setLoginRedirection('/custom-welcome-page', 'administrator');
}

/**
 * @implements hook_theme.
 */
function customblock_theme($existing, $type, $theme, $path)  {
  return [
    'artifacts_theme' => [
      'variables' => [
        'artifacts' => NULL,
      ]
    ]
  ];
}